# Generated by Django 5.2.17 on 2026-09-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('propietario', 'Propietario'), ('editor', 'Editor'), ('visualizador', 'Visualizador')], default='editor', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo')], default='pendiente', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores_detalle', to='modelado.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboraciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador de Proyecto',
                'verbose_name_plural': 'Colaboradores de Proyecto',
                'db_table': 'user_colaborador',
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
    ]
