# Generated by Django 5.2.17 on 2026-09-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, help_text='Código identificador correlativo único (ej. PROJ-001).', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del proyecto de modelado.', max_length=150)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción o propósito del proyecto.')),
                ('paquete_base', models.CharField(blank=True, default='', help_text='Paquete base para la generación de código (ej. com.example.proyecto).', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
