# Generated by Django 5.2.17 on 2026-09-07 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelado', '0001_initial'),
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, help_text='Colaboradores asignados al proyecto.', related_name='proyectos_colaborando', through='usuario.UserColaborador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='propietario',
            field=models.ForeignKey(help_text='Usuario creador y dueño del proyecto.', on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_propios', to=settings.AUTH_USER_MODEL),
        ),
    ]
