# Generated by Django 5.2.17 on 2026-09-10 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre conceptual de la entidad / clase.', max_length=150)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('papelera', 'Papelera')], default='activo', help_text='Estado de la entidad (activo, bloqueado para exclusión mutua, papelera).', max_length=20)),
                ('coord_x', models.FloatField(default=0.0, help_text='Posición X en el lienzo virtual de la pizarra.')),
                ('coord_y', models.FloatField(default=0.0, help_text='Posición Y en el lienzo virtual de la pizarra.')),
                ('ancho', models.FloatField(default=200.0, help_text='Ancho de la entidad en el lienzo.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece la entidad (agregación).', on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='modelado.proyecto')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entidad',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del atributo.', max_length=150)),
                ('tipo', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('long', 'Long'), ('double', 'Double'), ('boolean', 'Boolean'), ('date', 'Date')], default='string', help_text='Tipo de dato del atributo (string, integer, long, double, boolean, date).', max_length=20)),
                ('es_clave', models.BooleanField(default=False, help_text='Indica si el atributo es clave primaria o identificador.')),
                ('es_nulo', models.BooleanField(default=False, help_text='Indica si el atributo permite valores nulos.')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Posición u orden del atributo dentro de la entidad.')),
                ('entidad', models.ForeignKey(help_text='Entidad a la que pertenece el atributo (agregación).', on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='modelado.entidad')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
                'db_table': 'atributo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_relacion', models.CharField(blank=True, default='', help_text='Nombre opcional de la relación o verbo de conexión.', max_length=150)),
                ('tipo', models.CharField(choices=[('asociacion', 'Asociación'), ('agregacion', 'Agregación'), ('composicion', 'Composición'), ('generalizacion', 'Generalización / Herencia'), ('herencia', 'Herencia')], default='asociacion', help_text='Tipo de relación conceptual UML (asociacion, agregacion, composicion, generalizacion/herencia).', max_length=30)),
                ('entidad_destino', models.ForeignKey(help_text='Entidad destino de la relación.', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_destino', to='modelado.entidad')),
                ('entidad_origen', models.ForeignKey(help_text='Entidad origen de la relación.', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_origen', to='modelado.entidad')),
                ('proyecto', models.ForeignKey(help_text='Proyecto al que pertenece la relación (agregación).', on_delete=django.db.models.deletion.CASCADE, related_name='relaciones', to='modelado.proyecto')),
            ],
            options={
                'verbose_name': 'Relación',
                'verbose_name_plural': 'Relaciones',
                'db_table': 'relacion',
            },
        ),
    ]
