# Generated by Django 5.2.17 on 2026-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0003_entidad_atributo_relacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='datos_diagrama',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot del diagrama UML en formato JSON (posiciones, estado del lienzo y metadatos visuales).'),
        ),
    ]
