# Generated by Django 5.2.17 on 2026-09-10 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0004_proyecto_datos_diagrama'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='cardinalidad_destino',
            field=models.CharField(default='1', help_text="Multiplicidad o cardinalidad en la entidad de destino (ej. '1', '*', '0..1', '1..*').", max_length=20, validators=[django.core.validators.RegexValidator(message="La cardinalidad debe tener un formato UML válido (ej. '1', '*', '0..1', '1..*', '0..*').", regex='^([0-9]+|\\*|[0-9]+\\.\\.([0-9]+|\\*))$')]),
        ),
        migrations.AddField(
            model_name='relacion',
            name='cardinalidad_origen',
            field=models.CharField(default='1', help_text="Multiplicidad o cardinalidad en la entidad de origen (ej. '1', '*', '0..1', '1..*').", max_length=20, validators=[django.core.validators.RegexValidator(message="La cardinalidad debe tener un formato UML válido (ej. '1', '*', '0..1', '1..*', '0..*').", regex='^([0-9]+|\\*|[0-9]+\\.\\.([0-9]+|\\*))$')]),
        ),
    ]
