# Generated by Django 5.2.17 on 2026-09-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0005_relacion_cardinalidad_destino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacion',
            name='tipo',
            field=models.CharField(choices=[('asociacion', 'Asociación'), ('agregacion', 'Agregación'), ('composicion', 'Composición'), ('herencia', 'Herencia (Generalización)')], default='asociacion', help_text='Tipo de relación conceptual UML (asociacion, agregacion, composicion, herencia).', max_length=30),
        ),
    ]
