# Generated by Django 5.2.17 on 2026-09-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0006_alter_relacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='puerto_destino',
            field=models.CharField(blank=True, default='', help_text="Identificador del puerto en la entidad de destino (ej. 'bottom-0', 'left-2').", max_length=50),
        ),
        migrations.AddField(
            model_name='relacion',
            name='puerto_origen',
            field=models.CharField(blank=True, default='', help_text="Identificador del puerto en la entidad de origen (ej. 'top-0', 'right-1').", max_length=50),
        ),
    ]
