# Generated by Django 5.2.17 on 2026-09-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0007_relacion_puerto_destino_relacion_puerto_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='es_intermedia',
            field=models.BooleanField(default=False, help_text='Indica si la entidad es una tabla intermedia nacida a partir de una relación N:M (clase de asociación).'),
        ),
    ]
