# Generated by Django 5.2.17 on 2026-09-21 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0009_alter_relacion_cardinalidad_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='clase_asociacion',
            field=models.ForeignKey(blank=True, help_text='Entidad intermedia vinculada si la relación es N:M o clase de asociación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relaciones_asociadas', to='modelado.entidad'),
        ),
    ]
