# Generated by Django 5.2.17 on 2026-09-23 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelado', '0010_relacion_clase_asociacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacion',
            name='cardinalidad_destino',
            field=models.CharField(blank=True, default='', help_text="Multiplicidad o cardinalidad en la entidad de destino (ej. '1', '*', '0..1', '1..*').", max_length=20, validators=[django.core.validators.RegexValidator(message="La cardinalidad debe tener un formato UML válido (ej. '1', '*', '0..1', '1..*', '0..*').", regex='^([0-9]+|\\*|[0-9]+\\.\\.([0-9]+|\\*))$')]),
        ),
        migrations.AlterField(
            model_name='relacion',
            name='cardinalidad_origen',
            field=models.CharField(blank=True, default='', help_text="Multiplicidad o cardinalidad en la entidad de origen (ej. '1', '*', '0..1', '1..*').", max_length=20, validators=[django.core.validators.RegexValidator(message="La cardinalidad debe tener un formato UML válido (ej. '1', '*', '0..1', '1..*', '0..*').", regex='^([0-9]+|\\*|[0-9]+\\.\\.([0-9]+|\\*))$')]),
        ),
    ]
